// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgMzPQDCiJYmDG5SnjGxgnv6SUFJKpjGg',
    appId: '1:80174122191:web:a49a9f90593319fdeae3ba',
    messagingSenderId: '80174122191',
    projectId: 'instagram-clone-flutter-654a8',
    authDomain: 'instagram-clone-flutter-654a8.firebaseapp.com',
    storageBucket: 'instagram-clone-flutter-654a8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2KT4j3vP0zMcQ4RNMwJuGzVLRwfFvWao',
    appId: '1:80174122191:android:c806700498c997d7eae3ba',
    messagingSenderId: '80174122191',
    projectId: 'instagram-clone-flutter-654a8',
    storageBucket: 'instagram-clone-flutter-654a8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAwSwhQfLciDUKzvEJa4Svudx3nuv029A',
    appId: '1:80174122191:ios:6c03a71ad25c0c70eae3ba',
    messagingSenderId: '80174122191',
    projectId: 'instagram-clone-flutter-654a8',
    storageBucket: 'instagram-clone-flutter-654a8.appspot.com',
    iosBundleId: 'com.example.instagramCloneFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCAwSwhQfLciDUKzvEJa4Svudx3nuv029A',
    appId: '1:80174122191:ios:6c03a71ad25c0c70eae3ba',
    messagingSenderId: '80174122191',
    projectId: 'instagram-clone-flutter-654a8',
    storageBucket: 'instagram-clone-flutter-654a8.appspot.com',
    iosBundleId: 'com.example.instagramCloneFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAgMzPQDCiJYmDG5SnjGxgnv6SUFJKpjGg',
    appId: '1:80174122191:web:92f99cfd11c4c407eae3ba',
    messagingSenderId: '80174122191',
    projectId: 'instagram-clone-flutter-654a8',
    authDomain: 'instagram-clone-flutter-654a8.firebaseapp.com',
    storageBucket: 'instagram-clone-flutter-654a8.appspot.com',
  );
}
